name: build

on: push

jobs:
  build_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Install dep
      shell: bash
      run: |
        brew install sip pyqt5 ffmpeg
        python3 -m pip install -r requirements.txt
    - name: Install node pkg
      shell: bash
      run: |
        cd nodejs
        npm ci
        cd ..
    - name: Build
      shell: bash
      run: |
        python3 setup.py install
        make deploy
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
        retention-days: 3
